# where should data of players be stored
# default: YAML
# options: YAML, MYSQL
storageType: YAML

# settings for MySQl, ignore if you have storage set to MySQL
mySQL:
  # Where is MySQL on the internet
  host: localhost
  # port to MySQL
  port: 3306
  # database where data should be stored
  database: breakpoint
  # name of user THAT HAS PERMISSION TO WRITE/READ FROM DATABASE
  username: breakpoint
  # password of that user
  password: Breakp0intPa55w0rd
  # table of data (automaticly created if does not exist)
  table:
    players: breakpoint_players

#locations for some things (can be configured in-game
locations:
  # where should player spawn
  #      world name, x, y, z, yaw, pitch if config of this location and all others
  lobby: world,6.810,7.0,10.407,269.21353,-0.9816378
  shop: world,73.303,6.0,77.936,-89.89056,14.687969
  vipInfo: world,0.0,64.0,8.0,0.0,0.0
  moneyInfo: world,16.417,5.0,-0.828,-130.23354,4.3084373
  stafflist: world,0.0,64.0,8.0,0.0,0.0
# messages on lobby (can be configured in-game)
lobbyMessages: []
# language file (plugins/Breakpoint/lang/name.yml
lang: en
# Clanwars challenge game DO NOT CHNAGE !!
cwChallengeGame: CW
#only when clans should be able tto fight between eatch other (24 hour format) (clans will be able to fight eatch other between 18 and 21 hour)
cwBeginHour: 18 # start default: 18
cwEndHour: 21 # end default: 21
#if one team has 3 point then wins
cwWinLimit: 3 
# how many emeralds will they get for win
cwEmeraldsForTotalWin: 500
#random shop locationm ignore, i dont know what it does xD
randomshoploc: world,0,0,0,0
# time between boost melouns to spawn.
# let me explain the number so you dont mess up
# 1 second in MC is 20miliseconds, so 20 * 10 = 200 = every 10 seconds (has to be lower then 8 mins otherwise they will never spawn (they spawn only on sunday))
TimeForBoostMelounToSpawn: 200
#tokens bots
tokens:
  discord: 'token here m8'
  ts3:
    port: 10011
	ip: '192.168.1.100'
	sid: 0
	name: admin
	pass: passw0rd